name: Backend CI/CD

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Clean install
        run: |
          npm ci

  deploy:
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            clear_cache: true
            wait_deploy: true
            github_deployment: true
            deployment_environment: 'production'
            github_token: ${{ secrets.GITHUB_TOKEN }}
